name: MapBot
author: Maplef
version: 0.14.1-1.19_pre1
main: me.maplef.mapbotv4.Main
api-version: 1.18
depend:
  - Vault
commands:
  mapbot:
    description: commands of Mapbot_v4
    aliases: [mb]
permissions:
  mapbot.*:
    description: full access to mapbot commands
    children:
      mapbot.help: true
      mapbot.bind: true
      mapbot.hitokoto: true
      mapbot.weather: true
      mapbot.receive: true
      mapbot.stopserver: true
      mapbot.login: true
  mapbot.help:
    description: show help infomations
    default: true
  mapbot.bind:
    description: bind player's QQ number
    default: true
  mapbot.hitokoto:
    description: get a hitokoto
    default: true
  mapbot.weather:
    description: get weather of a city
    default: true
  mapbot.receive:
    description: receive messages from QQ group or not
    default: true
  mapbot.reload:
    description: reload mapbot
    default: op
  mapbot.stopserver:
    description: start a server stopping countdown, send all players to a safer server before shutdown
    default: op
  mapbot.login:
    description: login Mapbot QQ Account
    default: op
